#!/usr/bin/env bash
#A script written by BeneX-254 in September 4, 2024 under GNU GENERAL PUBLIC LICENSE

# TODO: come up with a better name
FZF_HEADER='
██╗░░░░░██╗██████╗░░░░░░░██╗░░██╗
██║░░░░░██║██╔══██╗░░░░░░╚██╗██╔╝
██║░░░░░██║██████╦╝█████╗░╚███╔╝░
██║░░░░░██║██╔══██╗╚════╝░██╔██╗░
███████╗██║██████╦╝░░░░░░██╔╝╚██╗
╚══════╝╚═╝╚═════╝░░░░░░░╚═╝░░╚═╝
'
CLI_NAME="${0##*/}"
CLI_VERSION="0.1.0"
CLI_AUTHOR="BeneX-254"
CLI_DIR="$(dirname "$(realpath "$0")")"

CONFIG_DIR="$HOME/.config/$CLI_NAME"
DBS_DIR="$CONFIG_DIR/DBS"
[ -d "$DBS_DIR" ] || mkdir -p "$DBS_DIR"

load_config() {
  READING_LIST_DB="$DBS_DIR/reading_list"
  PAUSED_LIST_DB="$DBS_DIR/paused_list"
  PLANING_LIST_DB="$DBS_DIR/planing_list"
  RE_READING_LIST_DB="$DBS_DIR/re_reading_list"
  COMPLETED_LIST_DB="$DBS_DIR/completed_list"
  DROPPED_LIST_DB="$DBS_DIR/dropped_list"
  DOCS_LIST_DB="$DBS_DIR/docs_list"
  RECENT_DB="$DBS_DIR/recent"

  DISOWN_READING_PROCESS="$(grep -s 'DISOWN_READING_PROCESS:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  [ -z "$DISOWN_READING_PROCESS" ] && DISOWN_READING_PROCESS=true

  PREFERRED_EDITOR="$(grep -s 'EDITOR:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  [ -z "$PREFERRED_EDITOR" ] && PREFERRED_EDITOR=${EDITOR:-open}

  PREFERRED_SELECTOR="$(grep -s 'PREFERRED_SELECTOR:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  [ -z "$PREFERRED_SELECTOR" ] && PREFERRED_SELECTOR="fzf"

  ENABLE_PREVIEW="$(grep -s 'ENABLE_PREVIEW:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  [ -z "$ENABLE_PREVIEW" ] && ENABLE_PREVIEW=true

  NO_OF_RECENT="$(grep -s 'NO-OF-RECENT:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  [ -z "$NO_OF_RECENT" ] && NO_OF_RECENT=30

  ROFI_THEME="$(grep -s 'ROFI_THEME:' "$CONFIG_DIR/${CLI_NAME}.conf" | sed 's/^#.*//g;s/^.*: //')"
  FZF_DEFAULT_OPTS=${LIBX_FZF_OPTS:-'
    --color=fg:#d0d0d0,fg+:#d0d0d0,bg:#121212,bg+:#262626
    --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00
    --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf
    --color=border:#262626,label:#aeaeae,query:#d9d9d9
    --border="rounded" --border-label="" --preview-window="border-rounded" --prompt="> "
    --marker=">" --pointer="◆" --separator="─" --scrollbar="│"
  '}
  export FZF_DEFAULT_OPTS

}

# notify-send -t $NOTIFICATION_DURATION -i "$notification_img" "Playing: $TITLE";
init_pretty_print() {
  if [ -t 1 ] && [ "$PRETTY_PRINT" = "y" ] || true; then
    # Check if stdout is a terminal
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    MAGENTA=$(tput setaf 5)
    CYAN=$(tput setaf 6)
    WHITE=$(tput setaf 7)
    BOLD=$(tput bold)
    BLACK=$(tput setaf 0)
    RESET=$(tput sgr0)
  fi

}

fzf-preview() {

  file=${1/#\~\//$HOME/}
  type=$(file --dereference --mime -- "$file")

  if [[ ! $type =~ image/ ]]; then
    if [[ $type =~ =binary ]]; then
      file "$1"
      exit
    fi

    # Sometimes bat is installed as batcat.
    if command -v batcat >/dev/null; then
      batname="batcat"
    elif command -v bat >/dev/null; then
      batname="bat"
    else
      cat "$1"
      exit
    fi

    ${batname} --style="${BAT_STYLE:-numbers}" --color=always --pager=never -- "$file"
    exit
  fi

  dim=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}
  if [[ $dim = x ]]; then
    dim=$(stty size </dev/tty | awk '{print $2 "x" $1}')
  elif ! [[ $KITTY_WINDOW_ID ]] && ((FZF_PREVIEW_TOP + FZF_PREVIEW_LINES == $(stty size </dev/tty | awk '{print $1}'))); then
    # Avoid scrolling issue when the Sixel image touches the bottom of the screen
    # * https://github.com/junegunn/fzf/issues/2544
    dim=${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))
  fi

  # 1. Use kitty icat on kitty terminal
  if [[ $KITTY_WINDOW_ID ]]; then
    # 1. 'memory' is the fastest option but if you want the image to be scrollable,
    #    you have to use 'stream'.
    #
    # 2. The last line of the output is the ANSI reset code without newline.
    #    This confuses fzf and makes it render scroll offset indicator.
    #    So we remove the last line and append the reset code to its previous line.
    kitty icat --clear --transfer-mode=memory --unicode-placeholder --stdin=no --place="$dim@0x0" "$file" | sed '$d' | sed $'$s/$/\e[m/'

    # 2. Use chafa with Sixel output
  elif command -v chafa >/dev/null; then
    chafa -f sixel -s "$dim" "$file"
    # Add a new line character so that fzf can display multiple images in the preview window
    echo

    # 3. If chafa is not found but imgcat is available, use it on iTerm2
  elif command -v imgcat >/dev/null; then
    # NOTE: We should use https://iterm2.com/utilities/it2check to check if the
    # user is running iTerm2. But for the sake of simplicity, we just assume
    # that's the case here.
    imgcat -W "${dim%%x*}" -H "${dim##*x}" "$file"

    # 4. Cannot find any suitable method to preview the image
  else
    file "$file"
  fi
}

confirm() {
  if command -v "gum" &>/dev/null; then
    gum confirm --default "$1"
  else
    read -r -p 'Are you sure you want to proceed [y/N]?: ' CONFIRMED
    case "$CONFIRMED" in
    y | Y)
      return 0
      ;;
    *)
      return 1
      ;;
    esac
  fi
}

launcher() {
  case "${PREFERRED_SELECTOR,,}" in
  *rofi*)
    if [ -z "$ROFI_THEME" ]; then
      rofi -sort -matching fuzzy -dmenu -i -width 1500 -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf
    else
      rofi -no-config -theme "$ROFI_THEME" -sort -matching fuzzy -dmenu -i -width 1500 -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf
    fi
    ;;
  *)
    fzf \
      --info=hidden \
      --layout=reverse \
      --height=100% \
      --prompt="Select Action: " \
      --header-first --header="$FZF_HEADER" \
      --exact --cycle
    ;;
  esac

}
launcher_with_preview() {
  case "${PREFERRED_SELECTOR,,}" in
  *rofi*)
    if [ -z "$ROFI_THEME" ]; then
      rofi -sort -matching fuzzy -dmenu -i -width 1500 -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf
    else
      rofi -no-config -theme "$ROFI_THEME" -sort -matching fuzzy -dmenu -i -p "" -mesg "Select Action" -matching fuzzy -sorting-method fzf
    fi
    ;;
  *)
    fzf \
      --info=hidden \
      --layout=reverse \
      --height=100% \
      --prompt="Select Book: " \
      --header-first --header="$FZF_HEADER" \
      --preview-window=left,35%,wrap --bind=right:accept \
      --expect=shift-left,shift-right --tabstop=1 \
      --cycle --exact \
      --ansi --preview="\
      if ! [ -z "{}" ] && ! [ {} = \"Exit\" ] && ! [ {} = \"Main Menu\" ];then\
        CALIBRE_DATA=\"\$(calibredb list --for-machine --fields all)\";\
        book=\$(echo \$CALIBRE_DATA |jq -r 'map(select(.title == \"'{}'\")) | .[0]');\
        book_title=\$(echo  \$book|jq -r '.title');\
        book_authors=\$(echo  \$book|jq -r '.authors');\
        book_tags=\$(echo  \$book|jq -r '.tags|join(\", \")');\
        book_cover=\$(echo  \$book|jq -r '.cover');\
        book_comments=\$(echo  \$book|jq -r '.comments');\
        book_langs=\$(echo  \$book|jq -r '.languages[]');\
        \
        init_pretty_print;\
        fzf-preview  \"\$book_cover\";
        echo \${MAGENTA}\${BOLD}Title:\${RESET} \$book_title;\
        echo \${MAGENTA}\${BOLD}Authors:\${RESET} \$book_authors;\
        echo -n \${MAGENTA}\${BOLD}Comments:\${RESET};\
        echo  \$book_comments|glow;\
        echo \${MAGENTA}\${BOLD}Tags:\${RESET} \$book_tags;\
        echo \${MAGENTA}\${BOLD}Languages:\${RESET} \$book_langs;\
      else\
        echo Loading;\
      fi;\
      " | tr -d "\n"
    ;;
  esac

}

user_lists_manager() {
  case "$1" in
  "Reading")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$READING_LIST_DB"; then
        echo Already in Reading List
        sleep 1
      else
        echo Adding to reading list...
        echo "$title" >>"$READING_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$READING_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$READING_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$READING_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;

  "Paused")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$PAUSED_LIST_DB"; then
        echo Already in paused List
        sleep 1
      else
        echo Adding to paused list...
        echo "$title" >>"$PAUSED_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$PAUSED_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$PAUSED_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$PAUSED_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;

  "Re-reading")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$RE_READING_LIST_DB"; then
        echo Already in re-reading List
        sleep 1
      else
        echo Adding to re-reading list...
        echo "$title" >>"$RE_READING_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$RE_READING_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$RE_READING_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$RE_READING_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;
  "Completed")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$COMPLETED_LIST_DB"; then
        echo Already in completed List
        sleep 1
      else
        echo Adding to completed list...
        echo "$title" >>"$COMPLETED_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$COMPLETED_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$COMPLETED_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$COMPLETED_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;

  "Docs")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$DOCS_LIST_DB"; then
        echo Already in docs List
        sleep 1
      else
        echo Adding to docs list...
        echo "$title" >>"$DOCS_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$DOCS_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$DOCS_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$DOCS_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;

  "Planing")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$PLANING_LIST_DB"; then
        echo Already in planing List
        sleep 1
      else
        echo Adding to planing list...
        echo "$title" >>"$PLANING_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$PLANING_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$PLANING_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$PLANING_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;
  "Dropped")
    if [ "$2" = "add" ]; then
      if grep "^${title}\$" -s -q <"$DROPPED_LIST_DB"; then
        echo Already in dropped List
        sleep 1
      else
        echo Adding to dropped list...
        echo "$title" >>"$DROPPED_LIST_DB"
      fi
    elif [ "$2" = "remove" ]; then
      if grep "^$title\$" -q <"$DROPPED_LIST_DB"; then
        if confirm "Are you sure you want to remove '$title' from  $1 List?"; then
          echo "removing from $1 List..."
          updated_list="$(grep --invert-match "^$title\$" <"$DROPPED_LIST_DB")"
          echo "$updated_list" | grep --extended-regexp '[[:alnum:]]+' >"$DROPPED_LIST_DB"
        fi
      else
        echo "$title is not in your $1 List"
        sleep 1
      fi
    fi
    ;;
  *)
    echo unknown option
    ;;
  esac
}

main() {

  # ---- main menu ----
  if [[ -n "$GO_DIRECTLY_TO" ]]; then
    action="$GO_DIRECTLY_TO"
    unset GO_DIRECTLY_TO
  else
    categories=$(calibredb list_categories --csv | tail -n +2 | cut -d , -f 1 | uniq)
    action=$(printf "Reading-List\nRecent\nPaused\nRe-reading\nPlaning\nCompleted\nDocs\nAll\nRandom\n%s\nEdit Config\nExit" "$categories" | launcher)
  fi
  case "$action" in
  # ---- user lists ----
  "Reading-List")
    titles="$(cat "$READING_LIST_DB")"
    ;;
  "Recent")
    titles="$(tac "$RECENT_DB")"
    ;;
  "Dropped")
    titles="$(cat "$DROPPED_LIST_DB")"
    ;;
  "Paused")
    titles="$(cat "$PAUSED_LIST_DB")"
    ;;
  "Completed")
    titles="$(cat "$COMPLETED_LIST_DB")"
    ;;
  "Re-reading")
    titles="$(cat "$RE_READING_LIST_DB")"
    ;;
  "Planing")
    titles="$(cat "$PLANING_LIST_DB")"
    ;;
  "Docs")
    titles="$(cat "$DOCS_LIST_DB")"
    ;;

  # ---- others ----
  "All")
    titles="$(echo "$CALIBRE_DATA" | jq -r '.[].title')"
    ;;
  "Random")
    titles="$(calibredb list --for-machine --fields=title | jq -r '.[].title' | shuf -n 30)"
    ;;

  # ---- calibre search ----
  "formats")
    series=$(calibredb list_categories --csv | grep "^formats" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "format:$series" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "format:$series" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "series")
    series=$(calibredb list_categories --csv | grep "^series" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "series:$series" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "series:$series" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "languages")
    language=$(calibredb list_categories --csv | grep "^languages" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "language:$language" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "language:$language" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "tags")
    tag=$(calibredb list_categories --csv | grep "^tags" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "tag:$tag" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "tag:$tag" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "rating")
    rating=$(calibredb list_categories --csv | grep "^rating" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "rating:$rating" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "rating:$rating" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "publisher")
    publisher=$(calibredb list_categories --csv | grep "^publisher" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "publisher:$publisher" --sort-by "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "publisher:$publisher" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "identifiers")
    identifier=$(calibredb list_categories --csv | grep "^identifiers" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "identifier:$identifier" --sort "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "identifier:$identifier" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  "authors")
    series=$(calibredb list_categories --csv | grep "^authors" | cut -d , -f 2 | launcher | tr -d '"')
    if [ -n "$SORT_BY" ]; then
      titles=$(calibredb list --search "author:$series" --sort "$SORT_BY" --for-machine --fields=title | jq '.[].title' -r)
    else
      titles=$(calibredb list --search "author:$series" --for-machine --fields=title | jq '.[].title' -r)
    fi
    ;;
  # ---- others ----
  "Edit Config")
    $PREFERRED_EDITOR "$CONFIG_DIR/${CLI_NAME}.conf"
    main
    load_config
    ;;
  "Exit")
    exit 0
    ;;
  *)
    echo invalid action
    sleep 1
    main
    ;;
  esac
  clear

  # book selection loop
  while true; do
    # ---- select book ----
    SHELL="bash"
    export SHELL
    export -f fzf-preview init_pretty_print
    if [ "$ENABLE_PREVIEW" = true ]; then
      title=$(printf "%s\nExit\nMain Menu" "$titles" | launcher_with_preview)
    else
      title=$(printf "%s\nExit\nMain Menu" "$titles" | launcher | tr -d "\n")
    fi
    [ "$title" = "Exit" ] && exit 0
    [ "$title" = "Main Menu" ] && break
    clear

    # ---- book actions ----
    while true; do
      action=$(
        printf "Read\nAdd To List\nRemove From List\nBack\nMain Menu\nExit" | launcher
      )
      case "$action" in
      "Read")
        # update recent list
        updated_recent_file_contents=$(grep --invert-match -s "^$title\$" <"$RECENT_DB" | tail -n "$NO_OF_RECENT" | grep --extended-regexp "[[:alnum:]]+")
        echo "$updated_recent_file_contents" >"$RECENT_DB"
        echo "$title" >>"$RECENT_DB"

        # open book
        book=$(calibredb list --for-machine --fields all | jq "map(select(.title == \"$title\")) | .[0]")
        book_path="$(echo "$book" | jq -r '.formats[0]')"
        open "$book_path" &>/dev/null &
        # disown
        [ "${PREFERRED_SELECTOR,,}" = "rofi" ] && wait
        [ "$DISOWN_READING_PROCESS" = true ] && [ "${PREFERRED_SELECTOR,,}" = "fzf" ] && disown
        [ "$DISOWN_READING_PROCESS" = false ] && [ "${PREFERRED_SELECTOR,,}" = "fzf" ] && wait
        ;;
      "Add To List")
        list_to_add_to=$(printf "Reading\nPaused\nPlaning\nRe-reading\nDocs\nCompleted\nDropped" | launcher)
        user_lists_manager "$list_to_add_to" "add"
        ;;
      "Remove From List")
        list_to_remove_from=$(printf "Reading\nPaused\nPlaning\nRe-reading\nDocs\nCompleted\nDropped" | launcher)
        user_lists_manager "$list_to_remove_from" "remove"
        ;;
      "Back")
        break
        ;;
      "Main Menu")
        MAIN=true
        break
        ;;
      "Exit")
        exit 0
        ;;

      *)
        echo invalid action
        sleep 1
        ;;
      esac
      clear
    done
    if [ "$MAIN" = true ]; then
      MAIN=false
      break
    fi
  done
  main
}

# ---- cli ----
byebye() {
  clear
  echo "Have a good day $USERNAME"
  exit 0
}
trap byebye INT EXIT TERM

usage() {
  printf "\
Usage: %s [arguments] [options] 

Commandline options override the config
Some of the options are directly passed to calibredb

Options:
  -s, --search
    search for a book based on calibredb search syntax
  -S, --sort-by 
    sort the books on a specified field
  -g, --go-directly-to
    open $CLI_NAME with a sub-menu pre-selected
  -e, --edit-config
    edit $CLI_NAME config file
  --rofi-theme <path>
    set the path to your rofi config file
  -d,--disown-reading-process
    disown the reading process so you can contine reading even if you close $CLI_NAME
  -D,--no-disown-reading-process
    don't disown the reading process hence when $CLI_NAME closes the app your using to read your book will also close
  -p <selector>,--preferred-selector <selector>
    set the preferred selector for $CLI_NAME to use
  --preview
    enable the preview window
  --no-preview
    disable the preview window
  -h, --help
    Show this help message and exit
  -v, --version
    print the $CLI_NAME version and exit

arguments:
  completions
    generates shell completions for $CLI_NAME

Examples:
  $CLI_NAME --search tag:chess --sort-by author
  $CLI_NAME --search tag:chess 
  $CLI_NAME --sort-by size 
  $CLI_NAME --go-directly-to Reading-List --sort-by size
  $CLI_NAME --go-directly-to Reading-List 

  $CLI_NAME completions --fish 

" "$CLI_NAME"
  exit "$1"
}

load_config
while [ $# -gt 0 ]; do
  case "$1" in
  -h | --help)
    usage 0
    ;;
  -v | --version)
    echo "$CLI_NAME $CLI_VERSION Copyright © 2024 $CLI_AUTHOR projects"
    exit 0
    ;;
  -e | --edit-config)
    $PREFERRED_EDITOR "$CONFIG_DIR/${CLI_NAME}.conf" || exit 1
    exit 0
    ;;
  -s | --search)
    [ -n "$2" ] || usage 1
    SEARCH="$2"
    CALIBRE_DATA="$(calibredb list --for-machine --fields=title --search "$SEARCH")"
    GO_DIRECTLY_TO="${GO_DIRECTLY_TO:-All}"
    shift
    ;;
  -g | --go-directly-to)
    [ -n "$2" ] || usage 1
    GO_DIRECTLY_TO="$2"
    shift
    ;;
  -S | --sort-by)
    [ -n "$2" ] || usage 1
    SORT_BY="$2"
    CALIBRE_DATA="$(calibredb list --for-machine --fields title --sort-by "$SORT_BY")"
    GO_DIRECTLY_TO="${GO_DIRECTLY_TO:-All}"
    shift
    ;;
  -p | --preferred-selector)
    [ -n "$2" ] || usage 1
    PREFERRED_SELECTOR="$2"
    shift
    ;;
  --preview)
    ENABLE_PREVIEW=true
    ;;
  --no-preview)
    ENABLE_PREVIEW=false
    ;;
  -d | --disown-reading-process)
    DISOWN_READING_PROCESS=true
    ;;
  -D | --no-disown-reading-process)
    DISOWN_READING_PROCESS=false
    ;;
  --rofi-theme)
    [ -n "$2" ] || usage 1
    ROFI_THEME="$2"
    shift
    ;;
  -E | --generate-desktop-entry)
    echo "
[Desktop Entry]
Name=$CLI_NAME
Type=Application
version=$CLI_VERSION
Path=$HOME
Comment=Read and manage your calibre books from the terminal
Terminal=false
Icon=$CLI_DIR/assets/logo.png
Exec=$0 --preferred-selector rofi
Categories=Education
    "
    exit 0
    ;;
  completions)
    [ -n "$2" ] || usage 1
    case "$2" in
    -f | --fish)
      echo "\
# --- functions ---
function _lib_x_complete_search
  for comp_line in (calibredb list_categories --csv) 
    set comp_key (echo \$comp_line|cut --delimiter , --fields 1)
    set comp_val (echo \$comp_line|cut --delimiter , --fields 2|tr -d '\"')
    echo "\$comp_key:\$comp_val"
  end
end

# --- completions ---
complete -c $CLI_NAME --no-files --arguments \"completions\" --condition 'not __fish_contains_opt search s sort-by S e edit-config p preferred-selector d disown-reading-process D no-disown-reading-process E generate-desktop-entry rofi-theme'

complete -c $CLI_NAME --no-files --short-option h --long-option help --description 'Print a short help text and exit'
complete -c $CLI_NAME --no-files --short-option v --long-option version --description 'Print a short version string and exit' --condition 'not __fish_seen_subcommand_from completions'

complete -c $CLI_NAME --no-files --short-option e --long-option edit-config --description 'Edit $CLI_NAME config file' --condition 'not __fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option p --long-option preferred-selector --description 'your preferred selector' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments 'fzf rofi'
complete -c $CLI_NAME --no-files --short-option d --long-option disown-reading-process --description 'disown the reading process' --condition 'not __fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option D --long-option no-disown-reading-process --description 'dont disown the reading process' --condition 'not __fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option E --long-option generate-desktop-entry --description 'generate desktop entry info' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --no-files --long-option preview --description 'enable preview window' --condition 'not __fish_seen_subcommand_from completions' 
complete -c $CLI_NAME --no-files --long-option no-preview --description 'disable preview window' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --force-files --long-option rofi-theme --description 'the path to your rofi config file' --condition 'not __fish_seen_subcommand_from completions' 

complete -c $CLI_NAME --no-files --short-option S --long-option sort-by --description 'Sort the books by a field' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments 'author_sort authors comments cover formats identifiers isbn languages last_modified pubdate publisher rating series series_index size tags template timestamp title uuid'
complete -c $CLI_NAME --no-files --short-option g --long-option go-directly-to --description 'Open $CLI_NAME with a sub-menu pre-selected' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments 'All Reading-List Paused Planing Re-reading Completed Docs Random authors formats identifiers languages  publisher rating series tags'
complete -c $CLI_NAME --no-files --short-option s --long-option search --description 'search for a book' --condition 'not __fish_seen_subcommand_from completions' --exclusive --arguments \"(_lib_x_complete_search)\"

complete -c $CLI_NAME --no-files --short-option z --long-option zsh --description 'print zsh completions' --condition '__fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option b --long-option bash --description 'print bash completions' --condition '__fish_seen_subcommand_from completions'
complete -c $CLI_NAME --no-files --short-option f --long-option fish --description 'print fish completions' --condition '__fish_seen_subcommand_from completions'
    "
      ;;
    -b | --bash)
      # TODO: write bash completions
      command ...
      ;;
    -z | --zsh)
      # TODO: write zsh completions
      command ...
      ;;
    -h | --help)
      echo "\
Generate shell completions for $CLI_NAME

Options:
  --fish
    print fish completions and exit
  --bash
    print bash completions and exit
  --zsh
    print zsh completions and exit

Example:
  $CLI_NAME completions --fish
  $CLI_NAME completions --bash
  $CLI_NAME completions --zsh
    "
      ;;
    *)
      echo "\
Generate shell completions for $CLI_NAME

Options:
  --fish
    print fish completions and exit
  --bash
    print bash completions and exit
  --zsh
    print zsh completions and exit

Example:
  $CLI_NAME completions --fish
  $CLI_NAME completions --bash
  $CLI_NAME completions --zsh
    "
      exit 1
      ;;

    esac
    exit 0
    ;;
  *)
    usage 1
    ;;
  esac
  shift
done
CALIBRE_DATA="${CALIBRE_DATA:-$(calibredb list --for-machine --fields title)}"

main
